/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAboutMe: typeof import('./src/components/AppAboutMe.vue')['default']
    AppContact: typeof import('./src/components/AppContact.vue')['default']
    AppCourse: typeof import('./src/components/AppCourse.vue')['default']
    AppExperience: typeof import('./src/components/AppExperience.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHero: typeof import('./src/components/AppHero.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    AppProjects: typeof import('./src/components/AppProjects.vue')['default']
    AppSkills: typeof import('./src/components/AppSkills.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
  }
}
